"""add language to posts

Revision ID: 865efb624b0c
Revises: a7b5a40ce108
Create Date: 2019-02-19 23:28:26.995073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865efb624b0c'
down_revision = 'a7b5a40ce108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
